package ec.edu.espe.amestore.view;

import ec.edu.espe.amestore.controller.CategoryController;
import ec.edu.espe.amestore.model.Category;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Sandoval
 */
public class JifrmCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form JifrmCategory
     */
    public JifrmCategory() {
        initComponents();
        this.setSize(new Dimension(400,200));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Jlcategory = new javax.swing.JLabel();
        TxtfCategory = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        JlWallpaper = new javax.swing.JLabel();

        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nueva Categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        Jlcategory.setText("Nombre de la Categoria:");
        getContentPane().add(Jlcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        TxtfCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtfCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(TxtfCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 180, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 30));
        getContentPane().add(JlWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtfCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtfCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtfCategoryActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Category category = new Category();
        CategoryController controlCategory = new CategoryController();
        
        if(TxtfCategory.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Complete todo los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            category.setDescription(TxtfCategory.getText().trim());
            category.setStatus(1);
            if(controlCategory.Save(category)){
                JOptionPane.showMessageDialog(this, "Se guardo Correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "Hubo un error al guardar");
            }
        }
        
        TxtfCategory.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlWallpaper;
    private javax.swing.JLabel Jlcategory;
    private javax.swing.JTextField TxtfCategory;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
